version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db16
    restart: always
    environment:
      POSTGRES_DB: db16
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
