# Generated by Django 5.2.5 on 2025-09-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("company_profile", models.TextField(blank=True, null=True)),
                ("history", models.TextField(blank=True, null=True)),
                ("issue_share", models.BigIntegerField(blank=True, null=True)),
                (
                    "financial_ratio_issue_share",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("charter_capital", models.BigIntegerField(blank=True, null=True)),
                ("outstanding_share", models.FloatField(blank=True, null=True)),
                ("foreign_percent", models.FloatField(blank=True, null=True)),
                ("established_year", models.IntegerField(blank=True, null=True)),
                ("no_employees", models.IntegerField(blank=True, null=True)),
                ("stock_rating", models.FloatField(blank=True, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("delta_in_week", models.FloatField(blank=True, null=True)),
                ("delta_in_month", models.FloatField(blank=True, null=True)),
                ("delta_in_year", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("public_date", models.DateTimeField(blank=True, null=True)),
                ("issue_date", models.DateTimeField(blank=True, null=True)),
                ("source_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="stock.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="industries",
            field=models.ManyToManyField(
                blank=True, related_name="companies", to="stock.industry"
            ),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "news_image_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "news_source_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price_change_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("public_date", models.BigIntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="stock.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Officers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("officer_name", models.CharField(max_length=255)),
                ("officer_position", models.CharField(max_length=255)),
                ("position_short_name", models.CharField(max_length=255)),
                (
                    "officer_owner_percent",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officers",
                        to="stock.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("sub_own_percent", models.FloatField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidiaries",
                        to="stock.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("exchange", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbols",
                        to="stock.company",
                    ),
                ),
                (
                    "industries",
                    models.ManyToManyField(
                        blank=True, related_name="symbols", to="stock.industry"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_holder", models.CharField(max_length=255)),
                ("quantity", models.BigIntegerField(default=0)),
                (
                    "share_own_percent",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
                ),
                ("update_date", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholders",
                        to="stock.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("share_holder", "company")},
            },
        ),
    ]
