# Generated by Django 5.2.5 on 2025-09-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_report", models.IntegerField(help_text="Năm báo cáo")),
                ("length_report", models.IntegerField(help_text="Kỳ báo cáo")),
                (
                    "current_assets_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "cash_and_cash_equivalents_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "short_term_investments_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "accounts_receivable_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("net_inventories", models.BigIntegerField(blank=True, null=True)),
                (
                    "other_current_assets_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "long_term_assets_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "long_term_loans_receivables_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("fixed_assets_bn_vnd", models.BigIntegerField(blank=True, null=True)),
                (
                    "long_term_investments_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "other_non_current_assets",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("total_assets_bn_vnd", models.BigIntegerField(blank=True, null=True)),
                ("liabilities_bn_vnd", models.BigIntegerField(blank=True, null=True)),
                (
                    "current_liabilities_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "long_term_liabilities_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("owners_equitybn_vnd", models.BigIntegerField(blank=True, null=True)),
                (
                    "capital_and_reserves_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "undistributed_earnings_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("minority_interests", models.BigIntegerField(blank=True, null=True)),
                (
                    "total_resources_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "prepayments_to_suppliers_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "short_term_loans_receivables_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "inventories_net_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "investment_and_development_funds_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("common_shares_bn_vnd", models.BigIntegerField(blank=True, null=True)),
                (
                    "paid_in_capital_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "long_term_borrowings_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "advances_from_customers_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "short_term_borrowings_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("good_will_bn_vnd", models.BigIntegerField(blank=True, null=True)),
                (
                    "long_term_prepayments_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "other_long_term_assets_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "other_long_term_receivables_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "long_term_trade_receivables_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_sheets",
                        to="stock.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_report", "-length_report"],
                "unique_together": {("symbol", "year_report", "length_report")},
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_report", models.IntegerField(help_text="Năm")),
                ("length_report", models.IntegerField(help_text="Kỳ")),
                (
                    "net_profit_loss_before_tax",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "depreciation_and_amortisation",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "provision_for_credit_losses",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "unrealized_foreign_exchange_gain_loss",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "profit_loss_from_investing_activities",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("interest_expense", models.BigIntegerField(blank=True, null=True)),
                (
                    "operating_profit_before_changes_in_working_capital",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "increase_decrease_in_receivables",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "increase_decrease_in_inventories",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "increase_decrease_in_payables",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "increase_decrease_in_prepaid_expenses",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("interest_paid", models.BigIntegerField(blank=True, null=True)),
                (
                    "business_income_tax_paid",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "net_cash_inflows_outflows_from_operating_activities",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "purchase_of_fixed_assets",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "proceeds_from_disposal_of_fixed_assets",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "loans_granted_purchases_of_debt_instruments_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "collection_of_loans_proceeds_sales_instruments_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "investment_in_other_entities",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "proceeds_from_divestment_in_other_entities",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("gain_on_dividend", models.BigIntegerField(blank=True, null=True)),
                (
                    "net_cash_flows_from_investing_activities",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "increase_in_charter_captial",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "payments_for_share_repurchases",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "proceeds_from_borrowings",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "repayment_of_borrowings",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "finance_lease_principal_payments",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("dividends_paid", models.BigIntegerField(blank=True, null=True)),
                (
                    "cash_flows_from_financial_activities",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "net_increase_decrease_in_cash_and_cash_equivalents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "cash_and_cash_equivalents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "foreign_exchange_differences_adjustment",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "cash_and_cash_equivalents_at_the_end_of_period",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flows",
                        to="stock.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_report", "-length_report"],
                "unique_together": {("symbol", "year_report", "length_report")},
            },
        ),
        migrations.CreateModel(
            name="IncomeStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_report", models.IntegerField(help_text="Năm")),
                ("length_report", models.IntegerField(help_text="Kỳ")),
                (
                    "revenue_yoy_percent",
                    models.FloatField(
                        blank=True, help_text="Doanh thu YoY (%)", null=True
                    ),
                ),
                (
                    "revenue_bn_vnd",
                    models.BigIntegerField(
                        blank=True, help_text="Doanh thu (Bn. VND)", null=True
                    ),
                ),
                (
                    "attribute_to_parent_company_bn_vnd",
                    models.BigIntegerField(
                        blank=True,
                        help_text="LN sau thuế CĐ công ty mẹ (Bn. VND)",
                        null=True,
                    ),
                ),
                (
                    "attribute_to_parent_company_yo_y_percent",
                    models.FloatField(
                        blank=True, help_text="Tăng trưởng LN CĐ mẹ YoY (%)", null=True
                    ),
                ),
                (
                    "financial_income",
                    models.BigIntegerField(
                        blank=True, help_text="Thu nhập tài chính (Bn. VND)", null=True
                    ),
                ),
                (
                    "interest_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí lãi vay (Bn. VND)", null=True
                    ),
                ),
                (
                    "sales",
                    models.BigIntegerField(
                        blank=True, help_text="Doanh thu bán hàng", null=True
                    ),
                ),
                (
                    "sales_deductions",
                    models.BigIntegerField(
                        blank=True, help_text="Các khoản giảm trừ", null=True
                    ),
                ),
                (
                    "net_sales",
                    models.BigIntegerField(
                        blank=True, help_text="Doanh thu thuần", null=True
                    ),
                ),
                (
                    "cost_of_sales",
                    models.BigIntegerField(
                        blank=True, help_text="Giá vốn hàng bán", null=True
                    ),
                ),
                (
                    "gross_profit",
                    models.BigIntegerField(
                        blank=True, help_text="Lợi nhuận gộp", null=True
                    ),
                ),
                (
                    "financial_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí tài chính", null=True
                    ),
                ),
                (
                    "gain_loss_from_joint_ventures",
                    models.BigIntegerField(
                        blank=True, help_text="LN/Lỗ liên doanh", null=True
                    ),
                ),
                (
                    "selling_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí bán hàng", null=True
                    ),
                ),
                (
                    "general_admin_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí QLDN", null=True
                    ),
                ),
                (
                    "operating_profit_loss",
                    models.BigIntegerField(
                        blank=True, help_text="LN từ HĐKD", null=True
                    ),
                ),
                (
                    "other_income",
                    models.BigIntegerField(
                        blank=True, help_text="Thu nhập khác", null=True
                    ),
                ),
                (
                    "other_income_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="Thu nhập/Chi phí khác", null=True
                    ),
                ),
                (
                    "net_other_income_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="LN/Lỗ thuần từ HĐ khác", null=True
                    ),
                ),
                (
                    "profit_before_tax",
                    models.BigIntegerField(
                        blank=True, help_text="LN trước thuế", null=True
                    ),
                ),
                (
                    "business_income_tax_current",
                    models.BigIntegerField(
                        blank=True, help_text="Thuế TNDN hiện hành", null=True
                    ),
                ),
                (
                    "business_income_tax_deferred",
                    models.BigIntegerField(
                        blank=True, help_text="Thuế TNDN hoãn lại", null=True
                    ),
                ),
                (
                    "net_profit_for_the_year",
                    models.BigIntegerField(
                        blank=True, help_text="LN thuần năm", null=True
                    ),
                ),
                (
                    "minority_interest",
                    models.BigIntegerField(
                        blank=True, help_text="Lợi ích cổ đông thiểu số", null=True
                    ),
                ),
                (
                    "attributable_to_parent_company",
                    models.BigIntegerField(
                        blank=True, help_text="LN thuộc về CĐ công ty mẹ", null=True
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_statements",
                        to="stock.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_report", "-length_report"],
                "unique_together": {("symbol", "year_report", "length_report")},
            },
        ),
        migrations.CreateModel(
            name="Ratio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_report", models.IntegerField()),
                ("length_report", models.IntegerField()),
                (
                    "st_lt_borrowings_equity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "debt_equity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "fixed_asset_to_equity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "owners_equity_charter_capital",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "asset_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "fixed_asset_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "days_sales_outstanding",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "days_inventory_outstanding",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "days_payable_outstanding",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "cash_cycle",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "inventory_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "ebit_margin_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "gross_profit_margin_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "net_profit_margin_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "roe_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "roic_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "roa_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("ebitda_bn_vnd", models.BigIntegerField(blank=True, null=True)),
                ("ebit_bn_vnd", models.BigIntegerField(blank=True, null=True)),
                (
                    "dividend_yield_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "cash_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "quick_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "interest_coverage",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "financial_leverage",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "market_capital_bn_vnd",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "outstanding_share_mil_shares",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "p_e",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "p_b",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "p_s",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "p_cash_flow",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "eps_vnd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "bvps_vnd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "ev_ebitda",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratios",
                        to="stock.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_report", "-length_report"],
                "unique_together": {("symbol", "year_report", "length_report")},
            },
        ),
    ]
