# Generated by Django 5.2.5 on 2025-09-26 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("seapay", "0001_initial"),
        ("setting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payusersymbollicense",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                db_comment="Auto-renew subscription that governs this license",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licenses",
                to="setting.symbolautorenewsubscription",
            ),
        ),
        migrations.AddField(
            model_name="payusersymbollicense",
            name="user",
            field=models.ForeignKey(
                db_comment="User Ã„â€˜Ã†Â°Ã¡Â»Â£c cÃ¡ÂºÂ¥p quyÃ¡Â»Â\x81n",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paywallet",
            name="user",
            field=models.ForeignKey(
                db_comment="ChÃ¡Â»Â§ vÃƒÂ\xad",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paywalletledger",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_comment="LiÃƒÂªn kÃ¡ÂºÂ¿t Ã„â€˜Ã†Â¡n hÃƒÂ\xa0ng khi lÃƒÂ\xa0 purchase/refund",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seapay.paysymbolorder",
            ),
        ),
        migrations.AddField(
            model_name="paywalletledger",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                db_comment="BÃ¡ÂºÂ¯t buÃ¡Â»â„¢c vÃ¡Â»â€ºi deposit (nÃ¡ÂºÂ¡p qua SePay)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="seapay.paypayment",
            ),
        ),
        migrations.AddField(
            model_name="paywalletledger",
            name="wallet",
            field=models.ForeignKey(
                db_comment="VÃƒÂ\xad bÃ¡Â»â€¹ Ã¡ÂºÂ£nh hÃ†Â°Ã¡Â»Å¸ng",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="seapay.paywallet",
            ),
        ),
        migrations.AddIndex(
            model_name="payorder",
            index=models.Index(fields=["user"], name="idx_pay_orders_user"),
        ),
        migrations.AddIndex(
            model_name="payorder",
            index=models.Index(fields=["status"], name="idx_pay_orders_status"),
        ),
        migrations.AddIndex(
            model_name="payorder",
            index=models.Index(fields=["created_at"], name="idx_pay_orders_created"),
        ),
        migrations.AddIndex(
            model_name="paypaymentattempt",
            index=models.Index(fields=["intent"], name="idx_pay_attempts_intent"),
        ),
        migrations.AddIndex(
            model_name="paybanktransaction",
            index=models.Index(fields=["intent"], name="idx_bank_tx_intent"),
        ),
        migrations.AddIndex(
            model_name="paybanktransaction",
            index=models.Index(
                fields=["reference_number"], name="idx_bank_tx_reference"
            ),
        ),
        migrations.AddIndex(
            model_name="paybanktransaction",
            index=models.Index(fields=["account_number"], name="idx_bank_tx_account"),
        ),
        migrations.AddIndex(
            model_name="paysymbolorder",
            index=models.Index(
                fields=["user", "status"], name="idx_symbol_orders_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="paysymbolorder",
            index=models.Index(fields=["status"], name="idx_symbol_orders_status"),
        ),
        migrations.AddIndex(
            model_name="paysymbolorder",
            index=models.Index(fields=["created_at"], name="idx_symbol_orders_created"),
        ),
        migrations.AddIndex(
            model_name="paypaymentintent",
            index=models.Index(
                fields=["user", "status"], name="idx_pay_intents_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="paypaymentintent",
            index=models.Index(fields=["order"], name="idx_pay_intents_order"),
        ),
        migrations.AddIndex(
            model_name="paypayment",
            index=models.Index(
                fields=["user", "created_at"], name="idx_pay_payments_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="paypayment",
            index=models.Index(fields=["intent"], name="idx_pay_payments_intent"),
        ),
        migrations.AddIndex(
            model_name="paypayment",
            index=models.Index(fields=["order"], name="idx_pay_payments_order"),
        ),
        migrations.AddIndex(
            model_name="paysymbolorderitem",
            index=models.Index(fields=["order"], name="idx_symbol_order_items_order"),
        ),
        migrations.AddIndex(
            model_name="paysymbolorderitem",
            index=models.Index(
                fields=["symbol_id"], name="idx_symbol_order_items_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="payusersymbollicense",
            index=models.Index(
                fields=["user", "symbol_id"], name="idx_symbol_lic_user_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="payusersymbollicense",
            index=models.Index(fields=["status"], name="idx_symbol_lic_status"),
        ),
        migrations.AddIndex(
            model_name="payusersymbollicense",
            index=models.Index(fields=["end_at"], name="idx_symbol_lic_end_at"),
        ),
        migrations.AddIndex(
            model_name="payusersymbollicense",
            index=models.Index(
                fields=["subscription"], name="idx_symbol_lic_subscription"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payusersymbollicense",
            unique_together={("user", "symbol_id", "start_at")},
        ),
        migrations.AddIndex(
            model_name="paywallet",
            index=models.Index(fields=["user"], name="idx_pay_wallets_user"),
        ),
        migrations.AddConstraint(
            model_name="paywallet",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_wallet"
            ),
        ),
        migrations.AddIndex(
            model_name="paywalletledger",
            index=models.Index(
                fields=["wallet", "created_at"], name="idx_ledger_wallet_created"
            ),
        ),
        migrations.AddIndex(
            model_name="paywalletledger",
            index=models.Index(fields=["payment"], name="idx_ledger_payment"),
        ),
        migrations.AddIndex(
            model_name="paywalletledger",
            index=models.Index(fields=["tx_type"], name="idx_ledger_tx_type"),
        ),
        migrations.AddIndex(
            model_name="paywalletledger",
            index=models.Index(fields=["order"], name="idx_ledger_order"),
        ),
    ]
