# Generated by Django 5.2.7 on 2025-10-06 04:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapay', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='paybanktransaction',
            table_comment='Bảng đối soát chủ động từ API SePay: id, số tiền, nội dung, tham chiếu...',
        ),
        migrations.AlterModelTableComment(
            name='payorder',
            table_comment='Đơn hàng có thể được thanh toán qua payment intents.',
        ),
        migrations.AlterModelTableComment(
            name='paypayment',
            table_comment='Bút toán thanh toán ở cấp gateway. Khi succeeded: nếu là nạp ví -> ghi credit ledger; nếu là order -> chuyển order sang paid, cấp license.',
        ),
        migrations.AlterModelTableComment(
            name='paypaymentattempt',
            table_comment='Một intent có thể có nhiều attempt (tạo lại QR, đổi số tiền...). Provider cố định: SePay.',
        ),
        migrations.AlterModelTableComment(
            name='paypaymentintent',
            table_comment='Một yêu cầu thu tiền. Provider cố định là SePay (chính sách hệ thống).',
        ),
        migrations.AlterModelTableComment(
            name='paysepaywebhookevent',
            table_comment='Inbox webhook của SePay. Ta luôn lưu thô trước, sau đó mới parse và xử lý để đảm bảo an toàn.',
        ),
        migrations.AlterModelTableComment(
            name='paysymbolorder',
            table_comment='Đơn hàng để mua quyền truy cập symbol. Có thể thanh toán trực tiếp qua SePay hoặc trừ ví nếu đã nạp.',
        ),
        migrations.AlterModelTableComment(
            name='paysymbolorderitem',
            table_comment='Chi tiết từng dòng sản phẩm trong đơn: symbol nào, thời hạn bao lâu.',
        ),
        migrations.AlterModelTableComment(
            name='payusersymbollicense',
            table_comment='Quyền sử dụng symbol để quyết định ai được nhận tín hiệu.',
        ),
        migrations.AlterModelTableComment(
            name='paywallet',
            table_comment='Mỗi user có 1 ví / 1 loại tiền. Tất cả thay đổi số dư đi qua pay_wallet_ledger.',
        ),
        migrations.AlterModelTableComment(
            name='paywalletledger',
            table_comment='Quy tắc: deposit phải có payment_id (SePay); purchase phải có order_id. Sổ cái là nguồn sự thật để tính balance.',
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='account_number',
            field=models.CharField(db_comment='STK nhận tiền', max_length=50),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='amount_in',
            field=models.DecimalField(db_comment='Tiền vào (nạp ví/ thanh toán)', decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='amount_out',
            field=models.DecimalField(db_comment='Tiền ra (ít dùng)', decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='attempt',
            field=models.ForeignKey(blank=True, db_comment='Khớp được attempt nào', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seapay.paypaymentattempt'),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='content',
            field=models.TextField(blank=True, db_comment='Nội dung CK (chứa order_code để auto-match)', null=True),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='intent',
            field=models.ForeignKey(blank=True, db_comment='Khớp được intent nào', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seapay.paypaymentintent'),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='payment',
            field=models.ForeignKey(blank=True, db_comment='Payment được tạo/chốt từ giao dịch này', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seapay.paypayment'),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='reference_number',
            field=models.CharField(blank=True, db_comment='Mã tham chiếu của ngân hàng', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='sepay_tx_id',
            field=models.BigIntegerField(db_comment='Khớp với provider_payment_id khi đã xử lý', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paybanktransaction',
            name='transaction_date',
            field=models.DateTimeField(db_comment='Thời gian giao dịch ngân hàng'),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='description',
            field=models.TextField(blank=True, db_comment='Mô tả đơn hàng'),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='metadata',
            field=models.JSONField(blank=True, db_comment='Dữ liệu bổ sung của đơn hàng', default=dict),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_comment='Trạng thái đơn hàng', default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='total_amount',
            field=models.DecimalField(db_comment='Tổng giá trị đơn hàng', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='user',
            field=models.ForeignKey(db_comment='Người tạo đơn hàng', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paypayment',
            name='amount',
            field=models.DecimalField(db_comment='Số tiền thanh toán', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='paypayment',
            name='intent',
            field=models.ForeignKey(blank=True, db_comment='Intent dẫn đến payment này', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seapay.paypaymentintent'),
        ),
        migrations.AlterField(
            model_name='paypayment',
            name='message',
            field=models.TextField(blank=True, db_comment='Ghi chú trạng thái (VD: Lý do failed)', null=True),
        ),
        migrations.AlterField(
            model_name='paypayment',
            name='metadata',
            field=models.JSONField(blank=True, db_comment='Payload bổ sung (bản đồ đối soát, sai số...)', default=dict),
        ),
        migrations.AlterField(
            model_name='paypayment',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='Đơn hàng liên quan (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seapay.paysymbolorder'),
        ),
        migrations.AlterField(
            model_name='paypayment',
            name='provider_payment_id',
            field=models.CharField(blank=True, db_comment='ID giao dịch SePay (sepay_tx_id) để tra soát', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paypayment',
            name='status',
            field=models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], db_comment='Trạng thái chốt sau khi đối soát', default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='paypayment',
            name='user',
            field=models.ForeignKey(db_comment='Người thực hiện thanh toán', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='account_name',
            field=models.CharField(blank=True, db_comment='Tên tài khoản nhận', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='account_number',
            field=models.CharField(blank=True, db_comment='STK nhận hoặc VA theo đơn', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='Hết hạn phiên attempt/QR', null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='intent',
            field=models.ForeignKey(db_comment='Thuộc intent nào', on_delete=django.db.models.deletion.CASCADE, to='seapay.paypaymentintent'),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='metadata',
            field=models.JSONField(blank=True, db_comment='Payload bổ sung', default=dict),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='provider_session_id',
            field=models.CharField(blank=True, db_comment='Mã phiên/khoá phía SePay nếu có', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='qr_image_url',
            field=models.TextField(blank=True, db_comment='Link ảnh QR động VietQR (SePay)', null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='qr_svg',
            field=models.TextField(blank=True, db_comment='Dữ liệu SVG QR nếu render trực tiếp', null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='status',
            field=models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], db_comment='Tiến trình attempt', default='requires_payment_method', max_length=30),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='transfer_amount',
            field=models.DecimalField(blank=True, db_comment='Số tiền hiển thị trên QR (có thể khóa cứng)', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentattempt',
            name='transfer_content',
            field=models.TextField(blank=True, db_comment='Nội dung CK chính xác để auto-match', null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='amount',
            field=models.DecimalField(db_comment='Số tiền phải trả', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='cancel_url',
            field=models.TextField(blank=True, db_comment='URL trở về khi hủy', null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='Hạn sử dụng intent/QR', null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='metadata',
            field=models.JSONField(blank=True, db_comment='Payload bổ sung (IP, UA, campaign...)', default=dict),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='Liên kết nếu là thanh toán đơn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seapay.paysymbolorder'),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='order_code',
            field=models.CharField(db_comment='Chuỗi đối soát CK (nội dung chuyển khoản). Cần duy nhất để match.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='purpose',
            field=models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('order_payment', 'Order Payment'), ('symbol_purchase', 'Symbol Purchase'), ('withdraw', 'Withdraw')], db_comment='wallet_topup (nạp ví) | order_payment (mua trực tiếp)', max_length=20),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='return_url',
            field=models.TextField(blank=True, db_comment='URL trở về khi thanh toán xong (nếu dùng webflow)', null=True),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='status',
            field=models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], db_comment='Trạng thái luồng thanh toán', default='requires_payment_method', max_length=30),
        ),
        migrations.AlterField(
            model_name='paypaymentintent',
            name='user',
            field=models.ForeignKey(db_comment='Ai đang thanh toán', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paysepaywebhookevent',
            name='payload',
            field=models.JSONField(db_comment='Lưu nguyên phần thân webhook để debug/đối soát'),
        ),
        migrations.AlterField(
            model_name='paysepaywebhookevent',
            name='process_error',
            field=models.TextField(blank=True, db_comment='Thông tin lỗi nếu xử lý thất bại', null=True),
        ),
        migrations.AlterField(
            model_name='paysepaywebhookevent',
            name='processed',
            field=models.BooleanField(db_comment='Đã xử lý phát sinh payment/ledger chưa', default=False),
        ),
        migrations.AlterField(
            model_name='paysepaywebhookevent',
            name='sepay_tx_id',
            field=models.BigIntegerField(db_comment='ID duy nhất từ SePay để idempotent (tránh xử lý trùng)', unique=True),
        ),
        migrations.AlterField(
            model_name='paysymbolorder',
            name='description',
            field=models.TextField(blank=True, db_comment='Mô tả/ghi chú đơn hàng', null=True),
        ),
        migrations.AlterField(
            model_name='paysymbolorder',
            name='order_id',
            field=models.UUIDField(db_comment='ID đơn hàng', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paysymbolorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet Balance'), ('sepay_transfer', 'SePay Transfer (QR/Bank)')], db_comment='wallet (trừ ví) hoặc sepay_transfer (QR/STK)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paysymbolorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_comment='Trạng thái vòng đời đơn', default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='paysymbolorder',
            name='total_amount',
            field=models.DecimalField(db_comment='Tổng tiền cần trả cho đơn', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='paysymbolorder',
            name='user',
            field=models.ForeignKey(db_comment='Người mua quyền truy cập symbol', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paysymbolorderitem',
            name='license_days',
            field=models.IntegerField(blank=True, db_comment='Số ngày cấp quyền sử dụng symbol; null = trọn đời', null=True),
        ),
        migrations.AlterField(
            model_name='paysymbolorderitem',
            name='metadata',
            field=models.JSONField(blank=True, db_comment='Thuộc tính thêm (phiên bản, biến thể, ...)', default=dict),
        ),
        migrations.AlterField(
            model_name='paysymbolorderitem',
            name='order',
            field=models.ForeignKey(db_comment='Đơn hàng chính', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seapay.paysymbolorder'),
        ),
        migrations.AlterField(
            model_name='paysymbolorderitem',
            name='order_item_id',
            field=models.UUIDField(db_comment='ID item đơn hàng', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paysymbolorderitem',
            name='price',
            field=models.DecimalField(db_comment='Đơn giá tại thời điểm mua', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='paysymbolorderitem',
            name='symbol_id',
            field=models.BigIntegerField(db_comment='Symbol là sản phẩm được bán'),
        ),
        migrations.AlterField(
            model_name='payusersymbollicense',
            name='end_at',
            field=models.DateTimeField(blank=True, db_comment='Thời điểm hết hạn; null = trọn đời', null=True),
        ),
        migrations.AlterField(
            model_name='payusersymbollicense',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='Đơn hàng tạo ra license này', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seapay.paysymbolorder'),
        ),
        migrations.AlterField(
            model_name='payusersymbollicense',
            name='start_at',
            field=models.DateTimeField(db_comment='Thời điểm kích hoạt', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payusersymbollicense',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_comment='Trạng thái quyền dùng symbol', default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='payusersymbollicense',
            name='symbol_id',
            field=models.BigIntegerField(db_comment='Symbol được cấp quyền'),
        ),
        migrations.AlterField(
            model_name='payusersymbollicense',
            name='user',
            field=models.ForeignKey(db_comment='User được cấp quyền', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paywallet',
            name='balance',
            field=models.DecimalField(db_comment='Số dư hiện tại, chỉ cập nhật qua ledger', decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='paywallet',
            name='currency',
            field=models.CharField(choices=[('VND', 'Vietnamese Dong'), ('USD', 'US Dollar')], db_comment='Loại tiền (VNĐ, USD...)', default='VND', max_length=10),
        ),
        migrations.AlterField(
            model_name='paywallet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_comment='active | suspended (khóa tạm thời)', default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='paywallet',
            name='user',
            field=models.ForeignKey(db_comment='Chủ ví', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='amount',
            field=models.DecimalField(db_comment='Luôn > 0; chiều thể hiện bằng is_credit', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='balance_after',
            field=models.DecimalField(db_comment='Số dư ngay sau giao dịch này', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='balance_before',
            field=models.DecimalField(db_comment='Số dư trước giao dịch', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='is_credit',
            field=models.BooleanField(db_comment='true: cộng ví; false: trừ ví'),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='metadata',
            field=models.JSONField(blank=True, db_comment='Payload bổ sung: ip, device, source, ...', default=dict),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='note',
            field=models.TextField(blank=True, db_comment='Diễn giải ngắn gọn cho bản ghi sổ cái'),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='Liên kết đơn hàng khi là purchase/refund', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seapay.paysymbolorder'),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='payment',
            field=models.ForeignKey(blank=True, db_comment='Bắt buộc với deposit (nạp qua SePay)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='seapay.paypayment'),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Nạp tiền (từ SePay)'), ('purchase', 'Mua bot'), ('refund', 'Hoàn tiền'), ('withdrawal', 'Rút tiền'), ('transfer_in', 'Chuyển đến'), ('transfer_out', 'Chuyển đi')], db_comment='Loại biến động: nạp/purchase/hoàn tiền/...', max_length=20),
        ),
        migrations.AlterField(
            model_name='paywalletledger',
            name='wallet',
            field=models.ForeignKey(db_comment='Ví bị ảnh hưởng', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='seapay.paywallet'),
        ),
    ]
