# Generated by Django 5.2.5 on 2025-09-26 04:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("seapay", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SymbolAutoRenewSubscription",
            fields=[
                (
                    "subscription_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol_id", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_activation", "Pending Activation"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending_activation",
                        max_length=20,
                    ),
                ),
                ("cycle_days", models.PositiveIntegerField(default=30)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("payment_method", models.CharField(default="wallet", max_length=30)),
                ("next_billing_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("grace_period_hours", models.PositiveIntegerField(default=12)),
                ("retry_interval_minutes", models.PositiveIntegerField(default=60)),
                ("max_retry_attempts", models.PositiveSmallIntegerField(default=3)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autorenew_subscriptions",
                        to="seapay.payusersymbollicense",
                    ),
                ),
                (
                    "last_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autorenew_subscriptions",
                        to="seapay.paysymbolorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbol_autorenew_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "symbol_autorenew_subscriptions",
                "db_table_comment": "Tracks auto-renew subscriptions for user symbols.",
            },
        ),
        migrations.CreateModel(
            name="SymbolAutoRenewAttempt",
            fields=[
                (
                    "attempt_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fail_reason", models.TextField(blank=True)),
                (
                    "charged_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "wallet_balance_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("ran_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seapay.paysymbolorder",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="setting.symbolautorenewsubscription",
                    ),
                ),
            ],
            options={
                "db_table": "symbol_autorenew_attempts",
                "db_table_comment": "History of auto-renew execution attempts.",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                (
                    "scope",
                    models.CharField(
                        choices=[("system", "System"), ("user", "User")],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "settings",
                "db_table_comment": "Generic key-value settings store supporting overrides.",
                "indexes": [
                    models.Index(fields=["key"], name="idx_settings_key"),
                    models.Index(fields=["scope"], name="idx_settings_scope"),
                ],
                "unique_together": {("key", "scope", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="symbolautorenewsubscription",
            index=models.Index(
                fields=["user", "symbol_id"], name="idx_autorenew_user_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="symbolautorenewsubscription",
            index=models.Index(fields=["status"], name="idx_autorenew_status"),
        ),
        migrations.AddIndex(
            model_name="symbolautorenewsubscription",
            index=models.Index(
                fields=["next_billing_at"], name="idx_autorenew_next_billing"
            ),
        ),
        migrations.AddConstraint(
            model_name="symbolautorenewsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending_activation", "active", "paused"])
                ),
                fields=("user", "symbol_id"),
                name="uq_autorenew_active_symbol",
            ),
        ),
        migrations.AddIndex(
            model_name="symbolautorenewattempt",
            index=models.Index(fields=["subscription"], name="idx_autorenew_attempt"),
        ),
        migrations.AddIndex(
            model_name="symbolautorenewattempt",
            index=models.Index(fields=["ran_at"], name="idx_autorenew_attempt_ran_at"),
        ),
    ]
