# Generated by Django 5.2.5 on 2025-09-26 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = []
