# Generated by Django 5.2.5 on 2025-10-02 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "webhook_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("tradingview", "TradingView"), ("custom", "Custom")],
                        default="tradingview",
                        help_text="Nguồn gửi webhook",
                        max_length=50,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Mã chứng khoán",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Toàn bộ payload nhận được từ webhook"),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        db_index=True, default=200, help_text="HTTP status code trả về"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        help_text="Response data trả về cho webhook caller",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Lỗi xảy ra (nếu có)", null=True
                    ),
                ),
                (
                    "users_notified",
                    models.IntegerField(
                        default=0, help_text="Số user đã được gửi notification"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "pay_webhook_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-created_at"],
                        name="pay_webhook_source_18ec54_idx",
                    ),
                    models.Index(
                        fields=["symbol", "-created_at"],
                        name="pay_webhook_symbol_b89c4a_idx",
                    ),
                    models.Index(
                        fields=["status_code", "-created_at"],
                        name="pay_webhook_status__04b7fb_idx",
                    ),
                ],
            },
        ),
    ]
