# Generated by Django 5.2.5 on 2025-09-26 05:04

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Timestamp when log was created"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        db_comment="Log level: debug, info, warning, error, critical",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        db_comment="Log channel: app, queue, payment, web, etc.",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(db_comment="Log message content")),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        db_comment="Structured metadata: user_id, request_id, ip, url, exception, stack",
                        default=dict,
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True, db_comment="Optional extra data", default=dict
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        db_comment="Environment: production, staging, local",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "logs",
                "db_table_comment": "System logs for auditing and debugging",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="idx_logs_created_at"),
                    models.Index(fields=["level"], name="idx_logs_level"),
                    models.Index(fields=["channel"], name="idx_logs_channel"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["context"], name="idx_logs_context_gin"
                    ),
                ],
            },
        ),
    ]
