# Generated by Django 5.2.7 on 2025-10-20 04:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='stock.symbol')),
            ],
            options={
                'db_table': 'bots',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trans_id', models.BigIntegerField(help_text='Lệnh mở và đóng cùng một trans_id')),
                ('trade_type', models.CharField(db_column='type', max_length=10)),
                ('direction', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Giá vào', max_digits=18, null=True)),
                ('entry_date', models.DateTimeField(help_text='Thời điểm có lệnh')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Giá thoát', max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Giá dừng lỗ', max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=2, help_text='Giá chốt lời', max_digits=18, null=True)),
                ('position_size', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, help_text='Phần trăm lợi nhuận', null=True)),
                ('max_duration', models.IntegerField(blank=True, null=True)),
                ('win_loss_status', models.CharField(blank=True, max_length=10, null=True)),
                ('action', models.CharField(help_text='Open | Close', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bots.bot')),
            ],
            options={
                'db_table': 'trades',
            },
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['symbol'], name='bots_symbol__01b0ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('name', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trans_id'], name='trades_trans_i_619b40_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['bot', 'entry_date'], name='trades_bot_id_cd6cd0_idx'),
        ),
    ]
