# Generated by Django 5.2.7 on 2025-10-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('short', 'Ngắn hạn'), ('medium', 'Trung hạn'), ('long', 'Dài hạn')], default='short', help_text='Loại bot: Ngắn hạn, Trung hạn, Dài hạn', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('symbol', 'bot_type')},
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['bot_type'], name='bots_bot_typ_62a125_idx'),
        ),
    ]
